name: jaffle_athena
version: '1.0'
config-version: 2

profile: jaffle_athena

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  jaffle_athena:
    +materialized: view
    +quote_columns: false
    +quoting:
      database: false
      schema: false
      identifier: false
    staging:
      +enabled: true
    marts:
      +enabled: true