jaffle_athena:
  target: dev
  outputs:
    dev:
      database: AwsDataCatalog
      region_name: eu-north-1
      s3_data_dir: s3://igor-athena-bucket-20250412/athena-tables/
      s3_staging_dir: s3://igor-athena-bucket-20250412/athena-results/
      schema: jaffle_athena
      type: athena
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
