version: 2

sources:
  - name: raw
    database: AwsDataCatalog
    quoting:
      database: false
      schema: false
      identifier: false
    schema: jaffle_athena
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments