version: 2

sources:
  - name: raw
    database: AwsDataCatalog
    quoting:
      database: false
      schema: false
      identifier: false
    schema: jaffle_athena
    tables:
      - name: raw_orders
        freshness:
          warn_after: { count: 12, period: month }
          error_after: { count: 24, period: month }
        loaded_at_field: order_date
      - name: raw_customers
      - name: raw_payments