jaffle_athena:
  outputs:
    dev:
      database: AwsDataCatalog
      region_name: eu-north-1
      s3_data_dir: s3://igor-athena-bucket-20250412/athena-tables/
      s3_staging_dir: s3://igor-athena-bucket-20250412/athena-results/
      schema: jaffle_athena
      threads: 1
      type: athena
  target: dev