name: Run dbt build on main

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * *'  # every day at 04:00 UTC

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-athena-community

      - name: Write dbt profile from secret
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml



      - name: Download previous manifest.json
        uses: actions/download-artifact@v2
        with:
          name: manifest
          path: .dbt-state

      - name: Run state-aware dbt build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dbt deps
          dbt compile
          dbt build --select state:modified+ --defer --state .dbt-state/

      - name: Upload new manifest.json
        uses: actions/upload-artifact@v2
        with:
          name: manifest
          path: target/manifest.json

      - name: Generate dbt docs
        run: dbt docs generate

      - name: Deploy dbt docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages