name: Daily dbt test + freshness check

on:
  schedule:
    - cron: '10 4 * * *'  # Daily at 04:10 UTC
  workflow_dispatch:

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET: igor-athena-bucket-20250412

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-athena-community

      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Run dbt deps
        run: dbt deps

      - name: Set timestamp vars
        id: ts
        run: |
          echo "year=$(date -u +%Y)" >> "$GITHUB_OUTPUT"
          echo "month=$(date -u +%m)" >> "$GITHUB_OUTPUT"
          echo "day=$(date -u +%d)" >> "$GITHUB_OUTPUT"

      - name: Run dbt tests
        run: dbt test --store-failures

      - name: Check source freshness
        run: dbt source freshness --output json

      - name: Upload results to S3 (partitioned paths)
        run: |
          aws s3 cp target/run_results.json s3://$BUCKET/test/year=${{ steps.ts.outputs.year }}/month=${{ steps.ts.outputs.month }}/day=${{ steps.ts.outputs.day }}/run_results.json
          aws s3 cp target/sources.json s3://$BUCKET/test/year=${{ steps.ts.outputs.year }}/month=${{ steps.ts.outputs.month }}/day=${{ steps.ts.outputs.day }}/sources.json

      - name: Fail on any test or freshness failure
        run: |
          if grep -q '"failures": [^0]' target/run_results.json || grep -q '"status": "error"' target/sources.json; then
            echo "🚨 Tests or freshness checks failed!"
            exit 1
          fi