name: Scheduled or Manual dbt run (state-aware)

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 4 * * *'  # daily at 04:00 UTC

  workflow_dispatch:
    inputs:
      triggerBuild:
        description: 'Trigger a dbt run manually'
        required: false
        type: boolean

jobs:
  dbt-state-aware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-athena-community

      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Try to download previous manifest (optional)
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: manifest
          path: .dbt-state

      - name: dbt build (state-aware)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          dbt deps
          dbt compile
          if [ -f .dbt-state/manifest.json ]; then
            echo "Previous manifest found — running state-aware build"
            dbt build --select state:modified+ --defer --state .dbt-state/
          else
            echo "No manifest found — running full build"
            dbt build
          fi
          dbt docs generate

      - name: Upload new manifest for next run
        uses: actions/upload-artifact@v2
        with:
          name: manifest
          path: target/manifest.json

      - name: Deploy dbt docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages