name: dbt build

on:
  push:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dbt + adapter
      run: pip install dbt-athena-community==1.9.4

    - name: Write dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

    - name: dbt deps
      run: dbt deps

    - name: dbt build
      run: dbt build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}