# name: Deploy dbt docs to GitHub Pages

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install dbt
#         run: pip install dbt-athena-community

#       - name: Create dummy dbt profile
#         run: |
#           mkdir -p ~/.dbt
#           echo "default:" > ~/.dbt/profiles.yml
#           echo "  target: dev" >> ~/.dbt/profiles.yml
#           echo "  outputs:" >> ~/.dbt/profiles.yml
#           echo "    dev:" >> ~/.dbt/profiles.yml
#           echo "      type: athena" >> ~/.dbt/profiles.yml
#           echo "      database: dummy" >> ~/.dbt/profiles.yml
#           echo "      s3_staging_dir: s3://dummy" >> ~/.dbt/profiles.yml
#           echo "      region_name: eu-west-1" >> ~/.dbt/profiles.yml
#           echo "      work_group: primary" >> ~/.dbt/profiles.yml

#       - name: Generate dbt docs
#         run: |
#           dbt deps
#           dbt compile
#           dbt docs generate

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./target