name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-athena-community

      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Generate dbt docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'eu-west-1' }}
        run: |
          dbt deps
          dbt compile
          dbt docs generate

      - name: Deploy docs to GitHub Pages
        run: |
          mkdir -p docs
          cp -r target/* docs/
          touch docs/.nojekyll
        shell: bash

      - name: Commit and push docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Auto-update dbt docs" || echo "No changes to commit"
          git push