name: Build and deploy dbt docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dbt
        run: pip install dbt-athena-community

      - name: Create dummy dbt profile
        run: |
          mkdir -p ~/.dbt
          echo 'default:
  target: dev
  outputs:
    dev:
      type: athena
      database: dummy
      s3_staging_dir: s3://dummy
      region_name: eu-west-1
      work_group: primary' > ~/.dbt/profiles.yml

      - name: Build dbt docs
        run: |
          dbt deps
          dbt compile
          dbt docs generate

      - name: Copy docs to root
        run: |
          mkdir -p ./docs
          cp -r target/* ./docs/
          touch ./docs/.nojekyll

      - name: Commit and push docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Update dbt docs" || echo "No changes"
          git push